//HintName: Splat.DI.Extensions.Registrations.SourceGenerated.cs

// <auto-generated />
namespace ReactiveMarbles.Locator
{
    internal static partial class LocatorRegistrations
    {
        static partial void SetupIOCInternal( ReactiveMarbles.Locator.IServiceLocator resolver) 
        {
            ReactiveMarbles.Locator.DefaultServiceLocator.AddService(() => new global::Test.TestConcrete((global::System.Lazy<global::Test.Service1>)resolver.GetService(typeof(global::System.Lazy<global::Test.Service1>))), typeof(global::Test.ITest), "Test2");
        }
    }
}