//HintName: Splat.DI.Extensions.Registrations.SourceGenerated.cs

// <auto-generated />
namespace ReactiveMarbles.Locator
{
    internal static partial class LocatorRegistrations
    {
        static partial void SetupIOCInternal( ReactiveMarbles.Locator.IServiceLocator resolver) 
        {
            resolver.AddLazySingleton<global::Test.ITest1>(() => new global::Test.TestConcrete1((global::Test.IService1)resolver.GetService<global::Test.IService1>(), (global::Test.IService2)resolver.GetService<global::Test.IService2>()), "Test2");
            resolver.AddLazySingleton<global::Test.ITest2>(() => new global::Test.TestConcrete2((global::Test.IService1)resolver.GetService<global::Test.IService1>(), (global::Test.IService2)resolver.GetService<global::Test.IService2>()), "Test2");
            resolver.AddLazySingleton<global::Test.ITest3>(() => new global::Test.TestConcrete3((global::Test.IService1)resolver.GetService<global::Test.IService1>(), (global::Test.IService2)resolver.GetService<global::Test.IService2>()), "Test2");
        }
    }
}