//HintName: Splat.DI.Extensions.Registrations.SourceGenerated.cs

// <auto-generated />
namespace ReactiveMarbles.Locator
{
    internal static partial class LocatorRegistrations
    {
        static partial void SetupIOCInternal(ReactiveMarbles.Locator.IServiceLocator resolver) 
        {
            resolver.AddLazySingleton<global::Test.ITest>(() => new global::Test.TestConcrete(resolver.GetService<global::Test.IService1>(), resolver.GetService<global::Test.IService2>()){ ServiceProperty1 = resolver.GetService<global::Test.IServiceProperty1>(), ServiceProperty2 = resolver.GetService<global::Test.IServiceProperty2>(), ServiceProperty3 = resolver.GetService<global::Test.IServiceProperty3>()} );
        }
    }
}