//HintName: Splat.DI.Extensions.Registrations.SourceGenerated.cs

// <auto-generated />
namespace ReactiveMarbles.Locator
{
    internal static partial class LocatorRegistrations
    {
        static partial void SetupIOCInternal(ReactiveMarbles.Locator.IServiceLocator resolver) 
        {
            resolver.AddService<global::Test.ITest>(() => new global::Test.TestConcrete(resolver.GetService<global::Test.IService1>(), resolver.GetService<global::Test.IService2>()){ ServiceProperty = resolver.GetService<global::Test.IServiceProperty>()} , "Test1");
        }
    }
}