//HintName: Splat.DI.Extensions.Registrations.SourceGenerated.cs

// <auto-generated />
namespace ReactiveMarbles.Locator
{
    internal static partial class LocatorRegistrations
    {
        static partial void SetupIOCInternal(ReactiveMarbles.Locator.IServiceLocator resolver) 
        {
            resolver.AddService<global::Test.IService1>(() => new global::Test.Service1(), "Test2");
            resolver.AddService<global::Test.IService2>(() => new global::Test.Service2(), "Test2");
        }
    }
}