//HintName: Splat.DI.Extensions.Registrations.SourceGenerated.cs

// <auto-generated />
namespace ReactiveMarbles.Locator
{
    internal static partial class LocatorRegistrations
    {
        static partial void SetupIOCInternal(ReactiveMarbles.Locator.IServiceLocator resolver) 
        {
            resolver.AddService<global::Test.ITest>(() => new global::Test.TestConcrete(resolver.GetService<global::Test.IService1>(), resolver.GetLazyService<global::Test.IService2>()){ ServiceProperty1 = resolver.GetService<global::Test.IServiceProperty1>(), ServiceProperty2 = resolver.GetService<global::Test.IServiceProperty2>(), ServiceProperty3 = resolver.GetService<global::Test.IServiceProperty3>()} , "Test1");
            resolver.AddService<global::Test.IService1>(() => new global::Test.Service1(), "Test1");
            resolver.AddLazySingleton<global::Test.IService2>(() => new global::Test.Service2(), "Test1");
        }
    }
}